package blogstore

const NO = "no"
const YES = "yes"

const POST_STATUS_DRAFT = "draft"
const POST_STATUS_PUBLISHED = "published"
const POST_STATUS_UNPUBLISHED = "unpublished"
const POST_STATUS_TRASH = "trash"

const POST_EDITOR_BLOCKAREA = "BlockArea"
const POST_EDITOR_BLOCKEDITOR = "BlockEditor"
const POST_EDITOR_MARKDOWN = "Markdown"
const POST_EDITOR_HTMLAREA = "HtmlArea"
const POST_EDITOR_TEXTAREA = "TextArea"

const POST_CONTENT_TYPE_MARKDOWN = "markdown"
const POST_CONTENT_TYPE_HTML = "html"
const POST_CONTENT_TYPE_PLAIN_TEXT = "plain_text"
const POST_CONTENT_TYPE_BLOCKS = "blocks"

const VERSIONING_TYPE_POST = "post"

const COLUMN_AUTHOR_ID = "author_id"
const COLUMN_CANONICAL_URL = "canonical_url"
const COLUMN_CONTENT = "content"
const COLUMN_CREATED_AT = "created_at"
const COLUMN_SOFT_DELETED_AT = "soft_deleted_at"
const COLUMN_ID = "id"
const COLUMN_IMAGE_URL = "image_url"
const COLUMN_FEATURED = "featured"
const COLUMN_MEMO = "memo"
const COLUMN_META_KEYWORDS = "meta_keywords"
const COLUMN_META_DESCRIPTION = "meta_description"
const COLUMN_META_ROBOTS = "meta_robots"
const COLUMN_METAS = "metas"
const COLUMN_PUBLISHED_AT = "published_at"
const COLUMN_STATUS = "status"
const COLUMN_SUMMARY = "summary"
const COLUMN_TITLE = "title"
const COLUMN_UPDATED_AT = "updated_at"
const COLUMN_COUNT = "count"
const COLUMN_DESCRIPTION = "description"
const COLUMN_NAME = "name"
const COLUMN_PARENT_ID = "parent_id"
const COLUMN_POST_ID = "post_id"
const COLUMN_SLUG = "slug"
const COLUMN_TAXONOMY_ID = "taxonomy_id"
const COLUMN_TERM_ID = "term_id"
const COLUMN_TERM_SEQUENCE = "sequence"

// Taxonomy types (pre-defined)
const TAXONOMY_CATEGORY = "category"
const TAXONOMY_TAG = "tag"
