package blogstore

const NO = "no"
const YES = "yes"

const POST_STATUS_DRAFT = "draft"
const POST_STATUS_PUBLISHED = "published"
const POST_STATUS_UNPUBLISHED = "unpublished"
const POST_STATUS_TRASH = "trash"

const POST_EDITOR_BLOCKAREA = "BlockArea"
const POST_EDITOR_BLOCKEDITOR = "BlockEditor"
const POST_EDITOR_MARKDOWN = "Markdown"
const POST_EDITOR_HTMLAREA = "HtmlArea"
const POST_EDITOR_TEXTAREA = "TextArea"

const COLUMN_AUTHOR_ID = "author_id"
const COLUMN_CANONICAL_URL = "canonical_url"
const COLUMN_CONTENT = "content"
const COLUMN_CREATED_AT = "created_at"
const COLUMN_SOFT_DELETED_AT = "soft_deleted_at"
const COLUMN_ID = "id"
const COLUMN_IMAGE_URL = "image_url"
const COLUMN_FEATURED = "featured"
const COLUMN_MEMO = "memo"
const COLUMN_META_KEYWORDS = "meta_keywords"
const COLUMN_META_DESCRIPTION = "meta_description"
const COLUMN_META_ROBOTS = "meta_robots"
const COLUMN_METAS = "metas"
const COLUMN_PUBLISHED_AT = "published_at"
const COLUMN_STATUS = "status"
const COLUMN_SUMMARY = "summary"
const COLUMN_TITLE = "title"
const COLUMN_UPDATED_AT = "updated_at"
